config/routes.rb
Rails.application.routes.draw do
  get 'pins/index'
  get '/tagged', to: "pins#tagged", as: :tagged
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :pins, only: [ :show, :index, :new, :create, :edit, :update ] do
    member do
      patch :visit
      patch :to_visit
      patch :public
      patch :private
    end
  end

  get '/search', to: "pages#search"

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pin.rb
class Pin < ApplicationRecord
  acts_as_taggable_on :tags
  ActsAsTaggableOn::Tag.most_used(10)
  ActsAsTaggableOn::Tag.least_used(10)
  belongs_to :user
  has_one_attached :photo
  attr_accessor :use_current_location, :lat, :lon

  after_initialize :set_default, if: :new_record?

  validates :name, presence: true
  validates :address, presence: true
  validates :visited, inclusion: [true, false]
  validates :private, inclusion: [true, false]

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address? && :if_not_geocoded?
  ICONS = {
    'utensils' => "#E63946",
    'ice-cream' => "#FDB9C8",
    'burger' => "#FFD700",
    'pizza-slice' => "#808000",
    'carrot' => "#FFA500",
    'mug-hot' => "#6B4423",
    'martini-glass' => "#4E2A84",
    'beer-mug-empty' => "#FFBF00",
    'bag-shopping' => "#00BFFF",
    'tree' => "#008000",
    'landmark' => "#808080",
    'book' => "#800000",
    'music' => "#800080",
    'gamepad' => "#00FF00",
    'dice' => "#DC143C",
    'bowl-food' => "#A67B5B",
    'bacon' => "#D2691E",
    'fish' => "#3FA9F5",
    'prescription-bottle-medical' => "#0CBABA",
    'cart-shopping' => "#FF1C00"
  }
  def blank_stars
    if rating.nil?
      5
    else
      5 - rating
    end
  end


  private

  def set_default
    self.visited ||= false
    self.private ||= false
  end

  def if_not_geocoded?
    self.longitude.nil? && self.latitude.nil?
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :pins
  has_many :tags, -> { distinct }, through: :pins
  has_many :all_tags, through: :pins, source: :tags
  has_one_attached :avatar

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def tag_pins
    pins.map do |pin|
      pin.tag_list
    end.flatten.uniq
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit::Authorization

  before_action :configure_permitted_parameters, if: :devise_controller?

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[username avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[username avatar])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end

  def search
    if params[:query]
      query = params[:query]
      url = "https://maps.googleapis.com/maps/api/place/textsearch/json?location=35.63409893106672%139.7080938092547&radius=90000&query=#{query}&language=en&key=#{ENV['GOOGLE_API_KEY']}"
      uri = URI(url)
      response = Net::HTTP.get_response(uri)
      google_place_data = JSON.parse(response.body)
      @info = google_place_data["results"]
    end
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  def index
    @pins = Pin.all
    @filters_list = %i[view query sort_by visited]
    ## Default Location: Le Wagon Tokyo
    # @here = [35.6339404, 139.7082188]
    ## end of Default
    if params["lat"] == nil
      ## Default Location: Le Wagon Tokyo
      @here = [35.6339404, 139.7082188]
    else
      @here = params["lat"].to_f, params["lon"].to_f
    end

    if params[:query].present?
      sql_subquery = "name ILIKE :query OR comments ILIKE :query"
      @pins = @pins.where(sql_subquery, query: "%#{params[:query]}%")
    elsif params[:sort_by] == 'name'
      @pins = @pins.order(:name)
    elsif params[:sort_by] == 'date'
      @pins = @pins.order(created_at: :desc)
    elsif params[:visited] == '1'
      @pins = @pins.where(visited: true)
    elsif params[:visited] == '0'
      @pins = @pins.where(visited: false)
    elsif params[:sort_by] == 'distance'
      @pins = @pins.to_a.sort_by! do |pin|
        pin.distance_to(@here)
      end
    elsif params[:tags]
      @pins = Pin.tagged_with(params[:tags])
      # raise
    end
    @pins = policy_scope(@pins)
    if @pins.class == ActiveRecord::Relation
      @markers = @pins.geocoded.map do |pin|
        {
          lat: pin.latitude,
          lng: pin.longitude,
          marker_html: render_to_string(partial: "marker", locals: { pin: pin }), # , locals: {pin: pin}
          info_html: render_to_string(partial: "info", locals: { pin: pin }) # , locals: {pin: pin}
        }
      end
    else
      @markers = @pins.geocoded.map do |pin|
        {
          lat: pin.latitude,
          lng: pin.longitude,
          marker_html: render_to_string(partial: "marker", locals: { pin: pin }), # , locals: {pin: pin}
          info_html: render_to_string(partial: "info", locals: { pin: pin }) # , locals: {pin: pin}
        }
      end
    end
    # raise
  end

  def show
    @pin = Pin.find(params[:id])
    authorize @pin
    @related_pins = @pin.find_related_tags
  end

  def new
    if params[:name]
      @pin = Pin.new(name: params[:name], address: params[:address], latitude: params[:latitude], longitude: params[:longitude])
    else
      @pin = Pin.new
    end
    authorize @pin
  end

  def create
    @pin = Pin.new(pin_params)
    # debugger
    if @pin.address == ""
      @results = Geocoder.search([pin_params[:lat], pin_params[:lon]])
      @pin.address = @results.first.display_name
      @pin.latitude = pin_params[:lat]
      @pin.longitude = pin_params[:lon]
    end
    @pin.user = current_user
    authorize @pin
    if @pin.save
      tags = params[:pin][:tag_ids]
      tags.each do |tag|
        # next if tag.blank?
        new_tag = ActsAsTaggableOn::Tag.find_by(name: tag)
        @pin.tag_list.add(new_tag)
        @pin.save
      end
      redirect_to pin_path(@pin)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @pin = Pin.find(params[:id])
    authorize @pin
  end

  def update
    @pin = Pin.find(params[:id])
    authorize @pin
    @pin.update(pin_params)
    tags = params[:pin][:tag_ids]
      tags.each do |tag|
        new_tag = ActsAsTaggableOn::Tag.where(id: tag.to_i)
        @pin.tag_list.add(new_tag)
        @pin.save
      end
    redirect_to pin_path(@pin)
  end

  def tagged
    if params[:tag].present?
      @pins = Pin.tagged_with(params[:tag])
    else
      @pins = Pin.all
    end
  end

  def visit
    @pin = Pin.find(params[:id])
    authorize @pin
    @pin.visited = true
    @pin.save
    redirect_to pin_path, status: :see_other, notice: "Pin marked as visited!"
  end

  def to_visit
    @pin = Pin.find(params[:id])
    authorize @pin
    @pin.visited = false
    @pin.save
    redirect_to pin_path, status: :see_other, notice: "Pin marked as non visited!"
  end

  def public
    @pin = Pin.find(params[:id])
    authorize @pin
    @pin.private = false
    @pin.save
    redirect_to pin_path, status: :see_other, notice: "Pin marked as public!"
  end

  def private
    @pin = Pin.find(params[:id])
    authorize @pin
    @pin.private = true
    @pin.save
    redirect_to pin_path, status: :see_other, notice: "Pin marked as private!"
  end

  private

  def pin_params
    params.require(:pin).permit(:photo, :name, :address, :longitude, :latitude, :comments, :icon, :rating, :visited, :use_current_location, :lat, :lon, :private, :tag_list)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def pins_path_with_params(new_params = {})
    pins_path(params.permit(@filters_list).merge(new_params))
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Basho</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet"
href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script
src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script
src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script
src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%# <link href="sticky-footer-navbar.css" rel="stylesheet"> %>
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192"  href="/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">
    <link rel="manifest" href="<%= asset_path 'manifest.json' %>">
    <%= render 'shared/ios_pwa_links' %>
  </head>
  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div id="homepage-background">
  <div class="container-sm homepage mx-auto">
    <div>
      <%= image_tag "basho-logo.png", :class => "homepage-content" %>
    </div>
    <div>
    <h2>A map of your best memories, past and yet to come</h2>
    </div>
    <div>
      <%= image_tag "basho-image2.png", :class => "homepage-content" %>
    </div>

    <div class="start-button">
      <h2><%= link_to "Start", pins_path, :id => "start" %></h2>
    </div>
      <p class="description">Curate your very own map of Tokyo with the places that matter to you. Tag, filter, sort and customize your pins just the way you want it.</p>
      <p>© 2023 Basho, Inc. All rights reserved.</p>
  </div>
</div>

app/views/pages/search.html.erb
<div class="search_form p-3 mb-4">
  <div class="text-center m-4">
    <p>Type the name or address of a place you'd like to add to your map</p>
  </div>
  <div class="d-flex justify-content-center m-4">
    <%= form_with url: search_path, method: :get, class: "d-flex" do %>
      <%= text_field_tag :query,
            params[:query],
            placeholder: "Name or address"
        %>
      <%= submit_tag "Search", name: "", class: "btn btn-primary crayola-pink" %>
    <% end %>
  </div>
</div>
<div>
  <% if params[:query] %>
    <% @info.each do |place| %>
      <div class="card shadow m-3 p-4">
        <h5><%= place["name"] %></h5>
        <%= place["formatted_address"] %>
        <% place["geometry"]["location"]["lat"] %>
        <% place["geometry"]["location"]["lng"] %>
        <%= link_to '', new_pin_path(name: place["name"], address: place["formatted_address"], latitude: place["geometry"]["location"]["lat"], longitude: place["geometry"]["location"]["lng"]), class: 'card-link' %>
      </div>
    <% end %>
  <% else %>
    <div class="d-flex justify-content-center align-items-center space">
      <%= image_tag "basho-image2.png", class: "search-bcg" %>
    </div>
  <% end %>
</div>

app/views/pins/_info.html.erb
<div>
  <div class="popup-photo">
    <img src="<%= pin.photo.attached? ? cl_image_path(pin.photo.key) : "https://res.cloudinary.com/dcqlc61be/image/upload/v1701220410/basho-placeholder_pewcwm.jpg"%>" style="object-fit: cover; width: 100vh;">
    <div class="popup-icon" style="border-color: <%= Pin::ICONS[pin.icon] %>; background-color: <%= Pin::ICONS[pin.icon] %>;">
      <i class='fa-solid fa-<%= pin.icon %> popup-icon2' style="background-color: <%= Pin::ICONS[pin.icon] %>;"></i>
    </div>
  </div>
  <div class="bg-white p-4">
    <h2><%= pin.name %></h2>
    <p><%= pin.address %></p>
    <div class="d-flex justify-content-flex-start gap-1">
      <% tags = pin.tag_list %>
      <% tags.each do |tag| %>
        <div class="tags"><%= tag %></div>
      <% end %>
    </div>
    <div class="d-flex justify-content-end gap-3">
      <div class="btn-sort">
        <%= link_to pin_path(pin.id) do %>
          <i class="fa-solid fa-eye"></i>
        <% end %>
      </div>
      <div class="btn-sort">
        <%= link_to edit_pin_path(pin.id) do %>
          <i class="fa-solid fa-pencil"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/pins/_list.html.erb
<div class="list-container">
  <main class="px-4">
    <div class="row justify-content-center list-margin">
      <% @pins.each do |pin| %>
        <div class="col-12">
          <div class="card mb-9 shadow my-2 p-0" >
            <div class="card-product">
              <% if pin.photo.attached? %>
                <%= cl_image_tag pin.photo.key, crop: :fill %>
              <% else %>
                <%= image_tag "https://res.cloudinary.com/dcqlc61be/image/upload/v1701220410/basho-placeholder_pewcwm.jpg", class: "", alt: "Card image cap", height: "60", crop: :fill %>
              <% end %>
              <div class="card-product-infos">
                <div class="d-flex justify-content-between">
                  <p class="card-text"><%= number_with_precision(pin.distance_to(@here), precision: 2) %> km</p>
                  <p class="card-text"><%= pin.created_at.strftime("%d, %b, %Y") %></p>
                </div>
                <h5 class="card-title"><%= truncate(pin.name, :length => 15) %></h5>
                <p class="card-text"><%= truncate(pin.address, :length => 25) %></p>
                <ul class="p-1">
                  <% card_tags = pin.tag_list %>
                  <% card_tags.each do |card_tag| %>
                    <div class="tags-show-card">
                      <li><%= card_tag %></li>
                    <%# </label> %>
                    </div>
                  <% end %>
                </ul>
              </div>
              <%= link_to '', pin_path(pin.id), class: 'card-link' %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </main>
</div>

app/views/pins/_marker.html.erb
<div class="marker">
  <span class="fa-stack fa-2x">
    <i class="fa-solid fa-location-pin fa-stack-2x" style="color: <%= Pin::ICONS[pin.icon] %>; text-shadow: 2px 2px 2px rgba(0, 0, 0, 0.3);"></i>
    <i class="fa-solid fa-<%= pin.icon %> fa-stack-1x" style="font-size: 22px; color: white; bottom: 4px;"></i>
  </span>
</div>

app/views/pins/index.html.erb
<%# MAP/LIST TOGGLE BUTTON %>
<div class="map-list-views <%= 'show-list' if params[:view] == "list" %>">
  <div class="d-flex justify-content-center bg-gray fixed-top">
    <%= link_to pins_path_with_params(view: 'map') do  %>
      <%= button_tag "map", class: "btn-toggle btn-toggle-map" %>
    <% end %>
    <%= link_to pins_path_with_params(view: 'list') do  %>
      <%= button_tag "list", class: "btn-toggle btn-toggle-list" %>
    <% end %>
  </div>
  <%# END MAP/LIST TOGGLE BUTTON %>
  <div class="filters-map fixed-top">
    <div class="d-flex justify-content-between mt-3 ms-0">
      <button class="btn-filters" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasExample" aria-controls="offcanvasExample">
        <i class="fa-solid fa-filter" style="color: #ffffff;"></i>
      </button>
      <%# <div class="btn-sort list-container mx-2"> %>
      <%# <%= link_to pins_path_with_params(view: 'list'), data: {"controller": "geolocate"} do  %>
        <%# <i class="fa-solid fa-location-crosshairs" style="color: #ffffff;"></i> %>
        <%# <% end %>
        <%# </div> %>
        <%# </div> %>
      </div>
      <div data-controller="filters" class="filters-map fixed-top">
        <%# FILTER BUTTON %>
        <div class="d-flex justify-content-between list-container mt-3">
          <button class="btn-filters" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasExample" aria-controls="offcanvasExample">
            <i class="fa-solid fa-filter" style="color: #ffffff;"></i>
          </button>
          <div class="btn-sort list-container mx-2">
            <%= link_to pins_path_with_params(view: 'list'), data: {"controller": "geolocate"} do %>
              <i class="fa-solid fa-location-crosshairs" style="color: #ffffff;"></i>
            <% end %>
          </div>
        </div>
        <%# END FILTER BUTTON %>
        <%# OFF-CANVAS FILTER SIDEBAR %>
        <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
          <div class="offcanvas-header">
            <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
          </div>
          <div class="offcanvas-body">
            <div>
              <%# FILTERS %>
              <div class="" data-filters-target="filtersCard">
                <div class="px-2">
                  <div class="d-flex justify-content-center gap-3">
                    <div>
                      <%= link_to pins_path_with_params(visited: 1), data: {"controller": "geolocate"} do  %>
                        <%= button_tag "Visited", class: "btn btn-visited" %>
                      <% end %>
                    </div>
                    <div>
                      <%= link_to pins_path_with_params(visited: 0), data: {"controller": "geolocate"} do  %>
                        <%= button_tag "Not visited", class: "btn btn-visited" %>
                      <% end %>
                    </div>
                  </div>
                  <div class="my-2">
                    <%= form_with url: pins_path, method: :get, html: { data: { turbo: 'false' } } do |f| %>
                      <%= f.text_field :query,
            # params[:query],
            class: "form-control my-3",
            placeholder: "Search" %>
                      <%= f.collection_check_boxes :tags,
                  current_user.tags.order(:name),
                  :name,
                  :name,
                  include_hidden: false do |b| %>
                        <%# <div class="d-flex justify-content-start"> %>
                        <p class="m-0"><%= b.label class:"tags-show-index" do %>
                            <span class="me-3"><%= current_user.all_tags.where(name: "#{b.text}").count %></span><%= b.check_box + b.text %>
                          <%end%></p>
                        <%# </div> %>
                      <% end %>
                    </div>
                    <div class="d-flex justify-content-between">
                      <%= f.submit "Search", class: "btn btn-primary" %>
                      <%= f.submit "X Reset", class: "btn btn-secondary" %>
                      <%#= submit_tag " Search ", name: "", class: "btn btn-primary" %>
                      <%#= submit_tag " X Reset ", name: "", class: "btn btn-secondary" %>
                    </div>
                  <% end %>
                </div>
              </div>
              <%# END FILTERS %>
            </div>
          </div>
        </div>
      </div>
      <%# END OFF-CANVAS FILTER SIDEBAR %>
      <%# SORTING %>
      <div class="d-flex justify-content-end mx-2">
        <div class="d-flex my-auto align-items-end pt-2 gap-2">
          <p class="my-auto list-container">Sort by:</p>
          <div class="btn-sort list-container" >
            <%= link_to pins_path_with_params(sort_by: :name), data: {"controller": "geolocate"} do  %>
              <i class="fa-solid fa-arrow-down-a-z" style="color: #ffffff;"></i>
            <% end %>
          </div>
          <div class="btn-sort list-container" >
            <%= link_to pins_path_with_params(sort_by: :date), data: {"controller": "geolocate"} do  %>
              <i class="fa-solid fa-calendar-plus" style="color: #ffffff;"></i>
            <% end %>
          </div>
          <div class="btn-sort list-container" >
            <%= link_to pins_path_with_params(sort_by: :distance), data: {"controller": "geolocate"} do  %>
              <i class="fa-solid fa-compass-drafting" style="color: #ffffff;"></i>
            <% end %>
          </div>
        </div>
      </div>
      <%# END SORTING %>
    </div>
    <div
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      <div data-map-target="mapbox" class="map-container position-fixed" style="width: 100%; height: 93%;"

    ></div>
      <div data-map-target="plus">
        <%# link_to new_pin_path(:lat => params[:lat], :lon => params[:lon]), data: {"controller": "get-position"} do %>
          <%= link_to search_path do %>
            <button class="btn btn-primary circle-button d-flex" style="font-size: 50px;">
              +
            </button>
          <% end %>
        </div>
      </div>
      <%= render "list" %>
    </div>

app/views/pins/show.html.erb
<div class="container-fluid">
  <div class="row justify-content-center">
    <div class="col-12 col-lg-6 p-0">
      <div class="d-flex justify-content-center">
        <img src="<%= @pin.photo.attached? ? cl_image_path(@pin.photo.key) : "https://res.cloudinary.com/dcqlc61be/image/upload/v1701220410/basho-placeholder_pewcwm.jpg" %>" width="100%" height="300" class="object-fit-cover" >
      </div>
      <br>
      <div class="px-4 col-12 col-md-8 col-xl-6 mx-auto">
        <div class="d-flex px-1">
          <div class="show-icon pr-4" style="color: <%= Pin::ICONS[@pin.icon] %>;">
            <%= "<i class='fa-solid fa-#{@pin.icon}'></i>".html_safe %>
          </div>
          <div class="row justify-content-start">
            <h1><%= @pin.name %></h1>
            <h5><%= @pin.address %></h5>
          </div>
        </div>
        <ul class="px-1 py-4">
          <% @pin.user_id = current_user %>
          <% tags = @pin.tag_list %>
          <% tags.each do |tag| %>
            <li class="tags"><%= tag %></li>
          <% end %>
        </ul>
        <hr>
        <div class="d-flex justify-content-between align-items-center">
          <% if @pin.visited %>
            <div class="tags-show">Visited</div>
          <% else %>
            <div class="tags-show">Not visited</div>
          <% end %>
          <div class="justify-content-end">
            <% @pin.rating.to_i.times do %>
              <i class="fa-solid fa-star"></i>
            <% end %>
            <% @pin.blank_stars.times do %>
              <i class="fa-regular fa-star"></i>
            <% end %>
          </div>
        </div>
        <div class="mb-3">
          <hr>
          <em><%=@pin.comments%></em>
          <hr>
          <div class="d-flex justify-content-between align-items-center">
            <% if @pin.private %>
              <div class="tags-show">Private</div>
            <% else %>
              <div class="tags-show">Public</div>
            <% end %>
            <div class="justify-content-end">
              <div class="btn-sort">
                <%= link_to edit_pin_path do %>
                  <i class="fa-solid fa-pencil"></i>
                <% end %>
              </div>
            </div>
          </div>
          <div class="row justify-content-center p-3">
            <a href="/pins/index" class="btn btn-primary">Back to my pins</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">